### PR TITLE
feat: drop support for Enterprise Server and Enterprise Cloud-specific APIs, and add support for 10 new APIs

### PR DESCRIPTION
**Pull request by timrogers**
* feat: add support for new "Delete an organization secret"  (`DELETE /organizations/{org}/codespaces/secrets/{secret_name}`) Codespaces API
* feat: add support for new "Remove selected repository from an organization secret" (`DELETE /organizations/{org}/codespaces/secrets/{secret_name}/repositories/{repository_id}`) Codespaces API
* feat: add support for new "List organization secrets" (`GET /organizations/{org}/codespaces/secrets`) Codespaces API
* feat: add support for new "Get an organization public key" (`GET /organizations/{org}/codespaces/secrets/public-key`) Codespaces API
* feat: add support for new "Get an organization secret" (`GET /organizations/{org}/codespaces/secrets/{secret_name}` ) Codespaces API
* feat: add support for new "List selected repositories for an organization secret" (`GET /organizations/{org}/codespaces/secrets/{secret_name}/repositories`) Codespaces API
* feat: add support for new "Get a Dependabot alert" API (`GET /repos/{owner}/{repo}/dependabot/alerts/{alert_number}`)
* feat: add support for new "List Dependabot alerts for a repository" API (`GET /repos/{owner}/{repo}/dependabot/alerts`)
* feat: add support for new "Update a Dependabot alert" API (`PATCH /repos/{owner}/{repo}/dependabot/alerts/{alert_number}`)
* feat: adds support for new "Create or update an organization secret" (`PUT /organizations/{org}/codespaces/secrets/{secret_name}` ) Codespaces API
* feat: add support for new "List selected repositories for an organization secret" (`GET /organizations/{org}/codespaces/secrets/{secret_name}/repositories`) Codespaces API
* feat: add support for new "Add selected repository to an organization secret" (`PUT /organizations/{org}/codespaces/secrets/{secret_name}/repositories/{repository_id}`) Codespaces API

BREAKING CHANGE: This drops support for a number of APIs which are only available in GitHub Enterprise Server (GHES) and GitHub Enterprise Cloud (GHEC). If you want to use these APIs and/or see TypeScript errors after upgrading to this version, you may need to start using the [`@octokit/plugin-enterprise-cloud`](https://github.com/octokit/plugin-enterprise-cloud.js) and/or [`@octokit/plugin-enterprise-server`](https://github.com/octokit/plugin-enterprise-server.js) packages.

### CODE REVIEW

**Comment by kfcampbell** [comment]
I've validated that I can use [@octokit/plugin-enterprise-cloud](https://github.com/octokit/plugin-enterprise-cloud.js) to perform operations for enterprise-cloud specific routes, e.g. getting an audit log for a test organization in a cloud enterprise:

```typescript
import { Octokit } from "@octokit/core";
import { enterpriseCloud } from "@octokit/plugin-enterprise-cloud";

async function main() {
	console.log("enterprise cloud version: " + enterpriseCloud.VERSION);
	const MyOctokit = Octokit.plugin(enterpriseCloud);
	// note that GITHUB_TOKEN needs to be exported in the environment
	const octokit = new MyOctokit({ auth: process.env.GITHUB_TOKEN });
        const res = await octokit.orgs.getAuditLog({
		org: "octokit-js-sdk-testing",
         })
	console.log(JSON.stringify(res));
}

main();
```

**Comment by kfcampbell** [comment]
I've also validated that I can use [@octokit/plugin-enterprise-server](https://github.com/octokit/plugin-enterprise-server.js) to perform operations for GHES-specific routes, e.g. getting enterprise stats for a GHES instance:

```typescript
import { Octokit } from "@octokit/core";
const {
	enterpriseServer36Admin,
} = require("@octokit/plugin-enterprise-server");

async function main() {
	const MyOctokit = Octokit.plugin(enterpriseServer36Admin);
	// note that GITHUB_TOKEN needs to be exported
	const octokit = new MyOctokit({
		auth: process.env.GITHUB_TOKEN,
		baseUrl: "https://REDACTED.ghe-test.com/api/v3",
	});

	// TODO: create a request using server-specific routes
	const res = await octokit.enterpriseAdmin.getAllStats({});
	console.log(JSON.stringify(res));

}

main();
```

With that, I've gained confidence that the GHES and GHEC plugins to Octokit.js are valid/operational.

**Review by kfcampbell — APPROVED** [review]
This change looks good to me given the above validation. The PR description already contains the "BREAKING CHANGE" string as specified in the [maintaining.md](https://github.com/octokit/octokit.js/blob/main/MAINTAINING.md).

**Comment by gr2m** [comment]
sorry I totally missed this PR 🤦🏼 I just merged https://github.com/octokit/types.ts/pull/463 which was the same change?

**Comment by gr2m** [comment]
done via #463

**Pull request closed without merging**
