### PR TITLE
feat: new `/orgs/{org}/properties/schema/{custom_property_name`, `GET /orgs/{org}/properties/schema`, `GET /orgs/{org}/properties/values`, `GET /orgs/{org}/rulesets/rule-suites/{rule_suite_id}`, `GET /orgs/{org}/rulesets/rule-suites`, `GET /repos/{owner}/{repo}/rulesets/rule-suites/{rule_suite_id}`, `POST /repos/{owner}/{repo}/actions/runs/{run_id}/force-cancel` endpoints

### PR DESCRIPTION
**Pull request by octokitbot**
Make sure to update the commits so that the merge results in helpful release notes, see [Merging the Pull Request & releasing a new version](https://github.com/octokit/rest.js/blob/main/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).

In general

- Avoid breaking changes at all costs
- If there are no typescript or code changes, use a `docs` prefix
- If there are typescript changes but no code changes, use `fix(typescript)` prefix
- If there are code changes, use `fix` if a problem was resolved, `feat` if new endpoints / parameters were added, and `feat(deprecation)` if a method was deprecated.

### CODE REVIEW

**Review by wolfy1339 — APPROVED** [review]

**Comment by wolfy1339** [comment]
@kfcampbell You forgot to update the generated files like in this PR

**Comment by kfcampbell** [comment]
:facepalm: That's done by `scripts/update-endpoints`?

**Comment by wolfy1339** [comment]
yeah

**Comment by OMartinez-NeT** [comment]
Hey @kfcampbell thanks for this contribution!! I have a question why when I try to use one of the types of this PR example:

```typescript
type GitHubCustomProperty =
  Endpoints["GET /orgs/{org}/properties/schema/{custom_property_name}"];
```

The result type has the property `response` as type unkwown:

```typescript
type GitHubCustomProperty = {
    parameters: {};
    request: {
        method: "GET";
        url: "/orgs/{org}/properties/schema/{custom_property_name}";
        headers: RequestHeaders;
        request: RequestRequestOptions;
    };
    response: unknown;
}
```

Whereas if I use another type example: 

```typescript
type listUserReposResponse = Endpoints["GET /repos/{owner}/{repo}"];
```

The result type has response populated:
```typescript
type listUserReposResponse = {
    parameters: {
        owner: string;
        repo: string;
    };
    request: {
        method: "GET";
        url: "/repos/{owner}/{repo}";
        headers: RequestHeaders;
        request: RequestRequestOptions;
    };
    response: OctokitResponse<...>;
}
```

Does it expect? Thanks!

**Comment by gr2m** [comment]
Can you share your `tsconfig` settings? I think you need to enable the strict mode

**Comment by oscar-vanta** [comment]
> Can you share your `tsconfig` settings? I think you need to enable the strict mode

Yes for sure:


```js
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "strict": true, 
    "noImplicitReturns": true, 
    "skipLibCheck": true, 
    "noFallthroughCasesInSwitch": true,
    "preserveConstEnums": true, 
    "noUnusedLocals": true, 
    "sourceMap": true,
    "inlineSources": true,
    "useUnknownInCatchVariables": false,
    "assumeChangesOnlyAffectDirectDependencies": true,
    "target": "es2022",
    "incremental": true,
    "lib": ["es2022"],
    "baseUrl": "build",
    "noErrorTruncation": false, 
    "esModuleInterop": true,
    "experimentalDecorators": true, 
    "emitDecoratorMetadata": true, 
    "pretty": true,
    "preserveWatchOutput": true,
    "resolveJsonModule": true
  }
}
```

**Comment by OMartinez-NeT** [comment]
> Can you share your `tsconfig` settings? I think you need to enable the strict mode
Yes for sure:


```js
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "strict": true, 
    "noImplicitReturns": true, 
    "skipLibCheck": true, 
    "noFallthroughCasesInSwitch": true,
    "preserveConstEnums": true, 
    "noUnusedLocals": true, 
    "sourceMap": true,
    "inlineSources": true,
    "useUnknownInCatchVariables": false,
    "assumeChangesOnlyAffectDirectDependencies": true,
    "target": "es2022",
    "incremental": true,
    "lib": ["es2022"],
    "baseUrl": "build",
    "noErrorTruncation": false, 
    "esModuleInterop": true,
    "experimentalDecorators": true, 
    "emitDecoratorMetadata": true, 
    "pretty": true,
    "preserveWatchOutput": true,
    "resolveJsonModule": true
  }
}
```

**Comment by gr2m** [comment]
I cannot reproduce the problem, see my [TypeScript playground](https://www.typescriptlang.org/play?ssl=8&ssc=1&pln=8&pc=49#code/JYWwDg9gTgLgBAbxgTzAUzgUQHYBNLDYwDOANHAGqYBKAygJIDyAcgL5wBmUEIcARAAEIAYxgQA1sBgB6FOmJ8AUIuERsxeADc0UYsDUAuOHLQQOlGgxZwAvPwCMAJgB0910sUm4AcSkAJAFcAIwBhAI0eAAVudFhkW0U4LDwCImIAbT5vTAAVOGloAHNiaQQi1mkwGJ0YYDQS4mEACzQQAENS4XCxEAB9KohYlF7sNpA0Vj4AXQBuZS9qesh1DDtfGEDQ7qjquMyoJbViNGmgA)

image

**Pull request merged**
