### PR TITLE
replace `{}` with `Record<string, never>`

### LINKED ISSUE #299: The meaning of ``{}`` in several declarations.
I'd like to ask what is the intent behind ``{}`` used in several declarations across ``@octokit/types``? For example [here](https://github.com/octokit/types.ts/blob/554c32f0980637acb4267998e099327951f4dafe/src/generated/Endpoints.ts#L20). Is it correct?

Whenever I use ``{}`` in my project, my linter fails with the message:

```console
14:13  error    Don't use `{}` as a type. `{}` actually means "any non-nullish value".
- If you want a type meaning "any object", you probably want `Record<string, unknown>` instead.
- If you want a type meaning "any value", you probably want `unknown` instead.
- If you want a type meaning "empty object", you probably want `Record<string, never>` instead  @typescript-eslint/ban-types
```

As I understand, the linter says that ``{}`` is mostly used by a mistake.

### PR DESCRIPTION
**Pull request by ptomulik**
Fixes #299

### CODE REVIEW

**Comment by ptomulik** [comment]
Note, that this may be a BC break. 

```typescript
function foo(t: {}) {
  console.log(t);
}
function bar(t: Record<string, never>) {
  console.log(t);
}

foo({foo: "foo"});
bar({foo: "foo"}); // error here
```

```console
error: Type 'string' is not assignable to type 'never'.
```

**Comment by ptomulik** [comment]
The clue is, that once a type is set to ``Record<string, never>``, no property can be added when extending it. Some examples:

```typescript
interface T extends Record<string, never> {
  foo: string; // error: Property 'foo' of type 'string' is not assignable to string index type 'never'.
}
```

```typescript
type T = Record<string, never> & {
  foo: string;
};

const r: T = {} // Type '{}' is not assignable to type 'T'.
                //  Property 'foo' is missing in type '{}' but required in type '{ foo: string; }'.
const t: T = { foo: "" } // error; Type '{ foo: string; }' is not assignable to type 'T'.
                         // Type '{ foo: string; }' is not assignable to type 'Record<string, never>'.
                         //    Property 'foo' is incompatible with index signature.
                         //      Type 'string' is not assignable to type 'never'.
```

It this is what ``@octokit/types`` really meant, then fine. But if the original intent was to return an "empty" record type that can be possibly extended, then ``Record<string, unknown>`` seems more appropriate. Also, ``Record<string, unknown>`` conceptually closer to ``{}``, so introducing it seems to be less harmful in terms of backward compatibility.

**Comment by gr2m** [comment]
Thanks for the explanations, it all makes sense. I think we have both use cases, sometimes we want objects to be extendable, sometimes not. I'll digg into it and test both changes with tests from some of `@octokit/types` dependands

**Comment by gr2m** [comment]
Alright. Sorry it took me so long to get back to you on your pull request! 

I think we can replace the `{}` with `Record<string, unknown>`, as we use the current `{}` in combination with other objects.

I'm not sure if this will have any side effects, I didn't test it. But if you'd like to make the change and nothing blows up let's just do it 😁

**Comment by gr2m** [comment]
Actually hold on, I think we want `{}` in this case, because `Record<unknow, string>` makes the resulting object accept any property, and we don't necessarily want that

```ts
type One = {
  foo: string
}

type Two = {}
type Three = Record<string, unknown>

const x: One & Two = {
  foo: "",
  // TS complains here, as it should I think.
  bar: ""
}

const y: One & Three = {
  foo: "",
  // TS does not complain here
  bar: ""
}
```

[playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gdtAvFA3gKClAZgexwLigGdgAnASzgHM0BfNNUSKAFQHccpkV6noWAFqQhIoAJQgBjHKQAmAHhIVqAGigBXOAGs4ONnAB8DaXBJQAHoXjQAZKw5dUGbHkIAiNyucAjAIal3NzpjHFNgKBArBCg7QWFRdExcAigPL0w-ANSg2iA)

**Comment by ptomulik** [comment]
This is funny:

```typescript
// An excerpt from @octokit/types/src/generated/Endpoints.ts
type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I
) => void
  ? I
  : never;

type ExtractParameters<T> = "parameters" extends keyof T
  ? UnionToIntersection<
      {
        [K in keyof T["parameters"]]: T["parameters"][K];
      }[keyof T["parameters"]]
    >
  : {};


// Test:
function foo<T extends ExtractParameters<{foo: 123}>>(t: T) {
  return t;
}

foo(10); // no error here
```

[playground](https://www.typescriptlang.org/play?#code/PTAEEEDtQUwDwMYwE4AcAuoBmyD2BbUAAVwXVwGsBLdYdAT1RgGdhnkFgBzGSFAQ3QwAJsACikYalxVI6ZgDp5AKAZNQAVUhVckACq4AknJTMYZHZAA8GgHygAvKAAUG2HCGTmofpHqgAfhcKAC5NAEpHewA3GWFQML5olEj4T2FvZ2VQUFDQWSwUUENlSIcYuOzA4qrEmGTkAG5lVUYYUDEPZH4yAAV+bvwYIWRmKz17JwAiVAH+IZHmKfd07woYelwsUD0qoK1LA2NF83RLKyqcnIBvS6ucgG0AaXzodc3tvQeZuYXTKYAugCwl8foNhv8Ac8Ac17jkAL4Pd5bHbfWbgxaAgF3Wy1UDXeHNFogHYsdAhZRYACukAsumwuFw4xWvAyHS6PXQ-Qxpis1ywjLCAEYAEwAZnhtlsznJO0itxyyGGVOQ0HQzXhLQFuGcQoADOFGqASZBcLBkHhkKAABYoGBAA)

**Comment by gr2m** [comment]
I'm not sure if there is anything we can do about it, it seems there is no ideal path here. Maybe it would be worth filing an issue on the TypeScript repository?

**Comment by ptomulik** [comment]
> I'm not sure if there is anything we can do about it, it seems there is no ideal path here. Maybe it would be worth filing an issue on the TypeScript repository?

If you mean "fixing" the ``{}`` type, then I think it's not gonna to be accepted.  As far as I remember, this is intended and documented behavior, and as linter warns, that type accepts anything that is not null. Not only objects. Use of ``{}`` is discouraged, and from experience of some authors, it is a common mistake.

**Comment by gr2m** [comment]
so it's either 

1. `{}`: better IntelliSense but accepting any value for request options
2. `Record<string, never>`: worse IntelliSense (any key are permitted) and confusing error message ("string is not assigneable to never")

Any better option?

**Comment by ptomulik** [comment]
Well then, let it be as is. I haven't accounted IntelliSence (vim fanatic :)).

**Comment by gr2m** [comment]
You really are missing out 😁 I think there are vi plugins to give you the TypeScript in-edotir IntelliSense magic

**Pull request closed without merging**
