### PR TITLE
feat: remove previews

### PR DESCRIPTION
**Pull request by wolfy1339**
Followup to https://github.com/octokit/endpoint.js/pull/382#issuecomment-1370197900
See also https://github.com/octokit/endpoint.js/pull/388 https://github.com/octokit/core.js/pull/538 https://github.com/octokit/plugin-paginate-rest.js/pull/486

----

### Before the change?

* Previews were documented

### After the change?

* Previews are no longer documented

### Other information

* This PR must be merged before all other ones in the Octokit JS repos

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [x] Yes (Please add the `Type: Breaking change` label)
- [ ] No

If `Yes`, what's the impact:  

* Removal of previews

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Review by oscard0m — APPROVED** [review]

**Comment by wolfy1339** [comment]
This unfortunately removes all previews. A follow up is needed to add it from GraphQL

**Comment by kfcampbell** [comment]
@wolfy1339 do you think it's worth a revert of this PR in the meantime? I'm not sure I understand the scope of the issue.

**Comment by wolfy1339** [comment]
I don't think a revert is warranted here.

We can probably handle it in the packages that have GraphQL themselves.

- `@octokit/core`
- `@octokit/graphql`
- `octokit` (octokit.js)

Types would need to be handled there

**Comment by nickfloyd** [comment]
It looks like this broke [plugin-enterprise-server.js](https://github.com/octokit/plugin-enterprise-server.js/pull/534) as well - I should've taken a closer look and remembered that there are still old supported versions of GHE that have references to previews.

**Comment by nickfloyd** [comment]
On the upside, GHE 3.2 (which had the majority of the preview implementation is deprecated: https://docs.github.com/en/enterprise-server@3.7/admin/all-releases

I'll need to check 3.3 (set to deprecate next week 01.18.2023) and 3.4 to make sure they are all gone from GHE versions - if that's the case we can just drop support for those versions as well and not rollback.

Thoughts?

**Comment by nickfloyd** [comment]
Update: Two instances have been left out in the REST API descriptions though they are defunct by v3.3.

@wolfy1339 It looks like we have two options here:
1. Revert
2. Clean up the files like [this](https://github.com/octokit/plugin-enterprise-server.js/blob/main/src/generated/ghe-32-endpoints.ts#L227) and deprecate v3.2 and v3.3 and move on.

Let me know your thoughts when you get the chance. Thanks!

**Comment by wolfy1339** [comment]
Sounds good

**Pull request merged**
